<?php
namespace App\Examples;

use App\Console\Command;
use App\Console\Input;
use App\Console\Output;

class SecondTest extends Command
{
    protected static string $name = 'test:second';

    public function execute(Input $input, Output $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}